server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@ljm5138_high?TNS_ADMIN=C://oracle//Wallet_ljm5138
    username: JUNGMIN
    password: Douzone12345

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    database: oracle
    properties:
      hibernate:
        format_sql: true
